version: '3'
services:     
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: 'neo4j/neo'
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: "desafioCenso"
      RABBITMQ_DEFAULT_PASS: "desafioCenso"
    ports:
      - "5672:5672"
      - "15672:15672"

  sender:
    image: sender
    build:
      context: .
      dockerfile: CensoRegional.Api.Sender/Dockerfile
    ports:
      - "20001:80"
    depends_on:
      neo4j:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: on-failure

  consumer:
    image: consumer
    build:
      context: .
      dockerfile: CensoRegional.Api.Consumer/Dockerfile
    ports:
      - "20000:80"
    depends_on:
      neo4j:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: on-failure